CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

%.o: %.cc 
	$(CC) -w -DLOG_TO_STDOUT=1 -I/usr/local/include/ -Ilibfreenect2/include -Ilibfreenect2/include/internal -Ilibfreenect2 -Ilibfreenect2/src/tinythread -I/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0 -I/usr/local/opt/jpeg-turbo/include -I/usr/local/Cellar/glfw3/3.2/include   -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -c -o $@ $< 

kinect_server: base64.o kinect_streams.o png.o websocketserver.o  
	$(CC) -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk -Wl,-search_paths_first -Wl,-headerpad_max_install_names  websocketserver.o base64.o kinect_streams.o png.o -o kinect_server libfreenect2/lib/libfreenect2.0.2.0.dylib /usr/local/Cellar/glfw3/3.2/lib/libglfw3.dylib -framework OpenGL /usr/local/Cellar/libusb/1.0.20/lib/libusb-1.0.dylib -lpthread -lwebsockets -lpng -framework VideoToolbox -framework CoreFoundation -framework CoreMedia -framework CoreVideo /usr/local/opt/jpeg-turbo/lib/libturbojpeg.dylib /usr/local/Cellar/glfw3/3.2/lib/libglfw3.dylib -framework OpenGL -L/usr/local/lib/  

#CMakeFiles/Protonect.dir/__/src/flextGL.cpp.o 
#  /Applications/Xcode.app/Contents/Developer/usr/bin/make -f examples/CMakeFiles/Protonect.dir/build.make examples/CMakeFiles/Protonect.dir/build
#  [ 90%] Building CXX object examples/CMakeFiles/Protonect.dir/Protonect.cpp.o
#  cd /Users/mtyka/src/libfreenect2/examples && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DEXAMPLES_WITH_OPENGL_SUPPORT=1 -DRESOURCES_INC -I/Users/mtyka/src/libfreenect2/include -I/Users/mtyka/src/libfreenect2/include/internal -I/Users/mtyka/src/libfreenect2 -I/Users/mtyka/src/libfreenect2/src/tinythread -I/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0 -I/usr/local/opt/jpeg-turbo/include -I/usr/local/Cellar/glfw3/3.2/include -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -I/Users/mtyka/src/libfreenect2/examples/../src  -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk   -o CMakeFiles/Protonect.dir/Protonect.cpp.o -c /Users/mtyka/src/libfreenect2/examples/Protonect.cpp
#  [ 93%] Building CXX object examples/CMakeFiles/Protonect.dir/viewer.cpp.o
#  cd /Users/mtyka/src/libfreenect2/examples && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DEXAMPLES_WITH_OPENGL_SUPPORT=1 -DRESOURCES_INC -I/Users/mtyka/src/libfreenect2/include -I/Users/mtyka/src/libfreenect2/include/internal -I/Users/mtyka/src/libfreenect2 -I/Users/mtyka/src/libfreenect2/src/tinythread -I/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0 -I/usr/local/opt/jpeg-turbo/include -I/usr/local/Cellar/glfw3/3.2/includev -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -I/Users/mtyka/src/libfreenect2/examples/../src  -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk   -o CMakeFiles/Protonect.dir/viewer.cpp.o -c /Users/mtyka/src/libfreenect2/examples/viewer.cpp
#  [ 96%] Building CXX object examples/CMakeFiles/Protonect.dir/__/src/flextGL.cpp.o
#  cd /Users/mtyka/src/libfreenect2/examples && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -DEXAMPLES_WITH_OPENGL_SUPPORT=1 -DRESOURCES_INC -I/Users/mtyka/src/libfreenect2/include -I/Users/mtyka/src/libfreenect2/include/internal -I/Users/mtyka/src/libfreenect2 -I/Users/mtyka/src/libfreenect2/src/tinythread -I/usr/local/Cellar/libusb/1.0.20/include/libusb-1.0 -I/usr/local/opt/jpeg-turbo/include -I/usr/local/Cellar/glfw3/3.2/include -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks -I/Users/mtyka/src/libfreenect2/examples/../src  -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk   -o CMakeFiles/Protonect.dir/__/src/flextGL.cpp.o -c /Users/mtyka/src/libfreenect2/src/flextGL.cpp
#  [100%] Linking CXX executable ../bin/Protonect
#  cd /Users/mtyka/src/libfreenect2/examples && /usr/local/Cellar/cmake/3.6.0_1/bin/cmake -E cmake_link_script CMakeFiles/Protonect.dir/link.txt --verbose=1
#  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++     [100%] Built target Protonect
#  /usr/local/Cellar/cmake/3.6.0_1/bin/cmake -E cmake_progress_start /Users/mtyka/src/libfreenect2/CMakeFiles 0

